import os, sys, time, uuid, logging, signal, librosa, soundfile as sf
from pathlib import Path
from dotenv import load_dotenv

PROJECT_DIRECTORY = os.path.dirname(os.path.abspath(__file__))

# voice_assistant is a proper package sitting next to this file, so its modules
# are imported through the package rather than via sys.path manipulation.
from voice_assistant.config import Config
from voice_assistant.audio import AudioManager
from voice_assistant.speech_to_text import SpeechToText
from voice_assistant.llm import LLMHandler
from voice_assistant.text_to_speech import TextToSpeech
from voice_assistant.wake_word import WakeWordDetector
from voice_assistant.spotify_controller import SpotifyController
from voice_assistant.clock import Clock
from voice_assistant.actions import ActionExecutor

# Loads environment variables from .env
load_dotenv()
# Creates the logs folder if it doesn't already exist.
os.makedirs(os.path.join(PROJECT_DIRECTORY, "logs"), exist_ok=True)
# Logging configuration for the entire application.
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
                    handlers=[logging.FileHandler(os.path.join(PROJECT_DIRECTORY, "logs", "smart_assistant.log")), logging.StreamHandler()])
# Logger for the SmartAssistant class
logger = logging.getLogger(__name__)

class SmartAssistant:
    def __init__(self):
        # Loads settings from config.yaml
        self.config = Config()

        # Retrieves the assistant's configuration section from config.yaml
        assistant_config = self.config.section("assistant")
        self.name = assistant_config.get("name", "Assistant")
        self.wake_word = assistant_config.get("wake_word", "Hey Assistant")

        # Retrieves the audio configuration section from config.yaml.
        # whisper_rate is set to a constant 16000 Hz, which is expected by Whisper.
        audio_config = self.config.section("audio")
        self.mic_rate = audio_config.get("sample_rate", 48000)
        self.whisper_rate = 16000

        # Creates or reuses a temporary folder for storing audio files generated by the voice assistant.
        self.temp_folder = Path(PROJECT_DIRECTORY) / "temp_audio"
        self.temp_folder.mkdir(exist_ok=True)
        self.tts_file = str(self.temp_folder / "response.wav")

        # Controls the main loop of the assistant. When set to False, the assistant will stop running.
        self.running = False

        logger.info("Loading modules...")
        
        # Sets up the audio manager with mic settings from config.
        self.audio = AudioManager(sample_rate=self.mic_rate, channels=audio_config.get("channels", 1), 
                                  chunk_size=audio_config.get("chunk_size", 2048))
        
        # Sets up speech-to-text with Whisper settings from config.
        whisper_config = self.config.section("whisper")
        self.stt = SpeechToText(model_size=whisper_config.get("model", "base.en"), device=whisper_config.get("device", "cpu"), 
                                compute_type=whisper_config.get("compute_type", "int8"), 
                                fallback_model=whisper_config.get("fallback_model", "tiny.en"))
        
        # Retrieves LLM configuration from config.yaml and passes it to LLMHandler.
        self.llm = LLMHandler(config=self.config, api_key=None)
        
        # Sets up text-to-speech with settings from config.
        self.tts = TextToSpeech(self.config)
        
        logger.info("Loading Spotify...")
        # Attempts to initialise the SpotifyController. If it fails, a warning is logged,
        # self.spotify falls back to None, and the assistant will continue to run without Spotify.
        try:
            self.spotify = SpotifyController(config=self.config)
        except Exception as e:
            logger.warning(f"Spotify initialisation failed: {e}")
            self.spotify = None

        # Sets up timers, which run on their own thread and call back here to speak when one goes off.
        self.clock = Clock(on_timer_finished=self._announce)

        # Sets up the action executor, which dispatches detected actions to the right controller.
        self.actions = ActionExecutor(spotify=self.spotify, clock=self.clock)
        
        # Sets up the wake word detector with sensitivity settings from config.
        self.thresholds = self.config.section("thresholds")
        self.wake = WakeWordDetector(config=self.config)

        # Register _shutdown to run on Ctrl + C (SIGINT) or a termination request (SIGTERM).
        # This ensures resources get cleaned up properly instead of the app dying abruptly .
        signal.signal(signal.SIGINT, self._shutdown) # Signal interrupt
        signal.signal(signal.SIGTERM, self._shutdown) # Signal termination
        
        logger.info(f"{self.name} ready!")

    def _announce(self, message):
        """
        Speaks a message which the user has scheduled, e.g. a timer.

        Uses its own audio file rather than the one the main loop uses, so a timer
        firing mid-conversation can't overwrite the reply being spoken. Shared ALSA
        output means both can play at once without fighting over the speaker.

        Args:
            message: What to say.
        """
        # A unique filename per announcement, so two going off close together can never overwrite each other's audio.
        announcement_file = str(self.temp_folder / f"announcement_{uuid.uuid4().hex[:8]}.wav")

        try:
            print(f"\n{self.name}: {message}")

            if self.tts.synthesise(message, announcement_file) is None:
                logger.error("Announcement synthesis failed")
                return

            audio_data, sample_rate = sf.read(announcement_file)
            if sample_rate != self.mic_rate:
                audio_data = librosa.resample(audio_data.astype("float32"),
                                              orig_sr=sample_rate, target_sr=self.mic_rate)
            self.audio.play(audio_data, sample_rate=self.mic_rate)
        except Exception as e:
            logger.error(f"Announcement failed: {e}")
        finally:
            # Announcement files are one-use, so they don't waste system storage.
            try:
                os.remove(announcement_file)
            except OSError:
                pass

    def _shutdown(self, *args):
        """
        Called automatically when the program receives Ctrl+C or a termination request.
        Closes the audio stream properly before exiting, so the microphone doesn't get left in a locked state.
        """
        logger.info("Shutting down...")
        self.running = False
        self.clock.stop()
        self.audio.close()
        sys.exit(0)

    def run(self):
        """
        Main loop of the voice assistant. This listens for the wake word, records audio until silence is detected,
        transcribes the audio to text, processes the query with the LLM, and executes any detected actions.
        """
        # Sets self.running to True to start the main loop and prints a confirmation message
        self.running = True
        print(f"\n{self.name} is ready. Say {self.wake_word} to activate.\n")

        # Main system loop that runs until self.running is set to False.
        # This loop uses try/except to catch any unexpected errors and log them rather than crashing the assistant.
        while self.running:
            try:
                self.wake.listen_once()
                print("Listening...")

                # Pauses the music for the whole interaction, not just while speaking.
                # This is so the microphone doesn't pick up the music while recording.
                # The finally block guarantees the music resumes after the interaction.
                if self.spotify:
                    self.spotify.pause_for_speech()
                try:
                    self._handle_interaction()
                finally:
                    if self.spotify:
                        self.spotify.resume_after_speech()

            # Catches any unexpected errors during the main loop, logs the error
            # and pauses briefly before continuing to listen for the wake word again.
            except Exception as e:
                logger.error(f"Error: {e}", exc_info=True)
                time.sleep(1)

    def _handle_interaction(self):
        """
        Handles one full interaction after the wake word: records the query,
        transcribes it, processes it with the LLM, runs any detected action,
        and speaks the response.
        """
        # Records audio after the wake word is detected until silence / a timeout occurs.
        audio_data = self.audio.record_until_silence(silence_duration=self.thresholds.get("silence_duration", 0.8),
                                                     silence_threshold=self.thresholds.get("silence_threshold", 0.05),
                                                     speech_timeout=self.thresholds.get("speech_timeout", 3.0),
                                                     timeout=self.thresholds.get("recording_timeout", 10.0))

        if audio_data is None or len(audio_data) == 0:
            return

        # Resamples the audio from the microphone's sample rate to the Whisper model's expected sample rate.
        if self.mic_rate != self.whisper_rate:
            audio_data = librosa.resample(audio_data.astype("float32"), orig_sr=self.mic_rate, target_sr=self.whisper_rate)

        # Transcribes the recorded audio using Whisper to text, Continues listening if no text is returned.
        transcription = self.stt.transcribe(audio_data)
        if not transcription or not transcription.get("text", "").strip():
            return

        # Retrieves and prints the transcribed text.
        text = transcription["text"]
        print(f"You: {text}")
        # Sends transcribed text to the LLM for processing, this returns a response and any detected actions.
        result = self.llm.process_query(text)
        response_text = result["response"]
        action = result.get("action")

        # If an action was detected, it is run through the action executor.
        # Its message is used as the spoken response if one was returned.
        if action:
            action_result = self.actions.execute(action)
            if action_result.get("message"):
                response_text = action_result["message"]

            # If the user explicitly asked for the music to pause, the automatic
            # resume at the end of the interaction shouldn't switch it back on.
            if self.spotify and action.get("type") == "spotify" and action.get("command") == "pause":
                self.spotify.cancel_resume()

        # Prints the response from the LLM, saves it as a WAV file, reads it, resamples it if necessary,
        # and plays it back to the user through the audio output.
        # If synthesis fails, playback is skipped rather than replaying a stale file.
        print(f"{self.name}: {response_text}")
        if self.tts.synthesise(response_text, self.tts_file) is None:
            logger.error("TTS synthesis failed, skipping playback")
            return
        tts_audio, tts_sr = sf.read(self.tts_file)
        if tts_sr != self.mic_rate:
            tts_audio = librosa.resample(tts_audio.astype("float32"), orig_sr=tts_sr, target_sr=self.mic_rate)
        self.audio.play(tts_audio, sample_rate=self.mic_rate)

# Runs the SmartAssistant if this script is executed directly. 
# This creates an instance of SmartAssistant and calls its run method to start the main loop.
if __name__ == "__main__":
    SmartAssistant().run()
