import os, sys, time, logging, signal, librosa, soundfile as sf
from pathlib import Path
from dotenv import load_dotenv
from config import Config

# Manually adds the voice_assistant directory to the Python path, 
# ensuring that modules from other directories can be imported without issues.
sys.path.insert(0, os.path.expanduser("~/voice_assistant"))
from audio import AudioManager
from speech_to_text import SpeechToText
from llm import LLMHandler
from text_to_speech import TextToSpeech
from wake_word import WakeWordDetector
from spotify_controller import SpotifyController

# Loads environment variables from .env
load_dotenv()
# Creates the logs folder if it doesn't already exist.
os.makedirs(os.path.expanduser("~/logs"), exist_ok=True)
# Logging configuration for the entire application.
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    handlers=[logging.FileHandler(os.path.expanduser("~/logs/smart_assistant.log")), logging.StreamHandler()])
# Logger for the SmartAssistant class
logger = logging.getLogger(__name__)

class SmartAssistant:
    def __init__(self):
        # Loads settings from config.yaml
        self.config = Config()

        # Retrieves the assistant's configuration section from config.yaml
        assistant_config = self.config.section("assistant")
        self.name = assistant_config.get("name", "Assistant")
        self.wake_word = assistant_config.get("wake_word", "Hey Assistant")

        # Retrieves the audio configuration section from config.yaml.
        # whisper_rate is set to a constant 16000 Hz, which is expected by Whisper.
        audio_config = self.config.section("audio")
        self.mic_rate = audio_config.get("sample_rate", 48000)
        self.whisper_rate = 16000

        # Creates or reuses a temporary folder for storing audio files generated by the voice assistant.
        self.temp_folder = Path(os.path.expanduser("~/temp_audio"))
        self.temp_folder.mkdir(exist_ok=True)
        self.tts_file = str(self.temp_folder / "response.wav")

        # Controls the main loop of the assistant. When set to False, the assistant will stop running.
        self.running = False

        logger.info("Loading modules...")
        
        # Sets up the audio manager with mic settings from config.
        self.audio = AudioManager(sample_rate=self.mic_rate, channels=audio_config.get("channels", 1), 
                                  chunk_size=audio_config.get("chunk_size", 2048))
        
        # Sets up speech-to-text with Whisper settings from config.
        whisper_config = self.config.section("whisper")
        self.stt = SpeechToText(model_size=whisper_config.get("model", "base.en"), device=whisper_config.get("device", "cpu"), 
                                compute_type=whisper_config.get("compute_type", "int8"), 
                                fallback_model=whisper_config.get("fallback_model", "tiny.en"))
        
        # Sets up the LLM handler with settings from config, passing in the assistant's name for the system prompt. 
        # The LLMHandler is responsible for processing user queries and generating responses.
        llm_config = self.config.section("llm")
        self.llm = LLMHandler(api_key=None, model=llm_config.get("model", "claude-haiku-4-5-20251001"), 
                              max_tokens=llm_config.get("max_tokens", 150), temperature=llm_config.get("temperature", 0.7), 
                              history_length=self.config.section("conversation").get("history_length", 5), assistant_name=self.name)
        
        # Sets up text-to-speech with settings from config.
        self.tts = TextToSpeech(self.config.data)
        
        logger.info("Loading Spotify...")
        # Attempts to initialize the SpotifyController. If it fails, a warning is logged, 
        # self.spotify falls back to None and the assistant will continue to run without Spotify.
        try:
            self.spotify = SpotifyController()
        except Exception as e:
            logger.warning(f"Spotify initialization failed: {e}")
            self.spotify = None
        
        # Sets up the wake word detector with sensitivity settings from config.
        self.thresholds = self.config.section("thresholds")
        self.wake = WakeWordDetector(sensitivity=self.thresholds.get("wake_word_confidence", 0.5))

        # Register _shutdown to run on Ctrl + C (SIGINT) or a termination request (SIGTERM).
        # This ensures resources get cleaned up properly instead of the app dying abruptly .
        signal.signal(signal.SIGINT, self._shutdown) # Signal interrupt
        signal.signal(signal.SIGTERM, self._shutdown) # Signal termination
        
        logger.info(f"{self.name} ready!")

    def _shutdown(self, *args):
        """
        Called automatically when the program receives Ctrl+C or a termination request.
        Closes the audio stream properly before exiting, so the microphone doesn't get left in a locked state.
        """
        logger.info("Shutting down...")
        self.running = False
        self.audio.close()
        sys.exit(0)

    def _execute_spotify_action(self, action):
        """
        Executes a Spotify action based on the command detected in the user's query.
        Returns a dictionary indicating success or failure, and any relevant messages.
        The action dictionary is provided by the LLMHandler's _parse_action method, 
        which interprets user queries and maps them to specific Spotify commands.
        """
        command = action.get("command")
        if command == "play":
            query = action.get("query")
            return self.spotify.play(query)
        elif command == "pause":
            return self.spotify.pause()
        elif command == "skip":
            return self.spotify.skip()
        elif command == "previous":
            return self.spotify.previous()
        elif command == "current":
            result = self.spotify.current_track()
            # If the current track information is successfully retrieved, return the track and artist details.
            if result.get("success"):
                return {"success": True, "message": f"Playing {result['track']} by {result['artist']}"}
            return result
        # If the command is not recognised, return a failure response.
        return {"success": False}

    def run(self):
        """
        Main loop of the voice assistant. This listens for the wake word, records audio until silence is detected,
        transcribes the audio to text, processes the query with the LLM, and executes any detected actions.
        """
        # Sets self.running to True to start the main loop and prints a confirmation message
        self.running = True
        print(f"\n{self.name} is ready. Say {self.wake_word} to activate.\n")

        # Main system loop that runs until self.running is set to False.
        # This loop uses try/except to catch any unexpected errors and log them rather than crashing the assistant.
        while self.running:
            try:
                self.wake.listen_once()
                print("Listening...")

                # Records audio after the wake word is detected until silence is detected or a timeout occurs.
                audio_data = self.audio.record_until_silence(silence_duration=self.thresholds.get("silence_duration", 2.0), 
                                                             timeout=self.thresholds.get("recording_timeout", 10.0))
                if audio_data is None or len(audio_data) == 0:
                    continue
                # Resamples the audio from the microphone's sample rate to the Whisper model's expected sample rate.
                if self.mic_rate != self.whisper_rate:
                    audio_data = librosa.resample(audio_data.astype("float32"), orig_sr=self.mic_rate, target_sr=self.whisper_rate)
                # Transcribes the recorded audio using Whisper to get text, If no text is detected, it continues listening
                transcription = self.stt.transcribe(audio_data)
                if not transcription or not transcription.get("text", "").strip():
                    continue
                # Retrieves and prints the transcribed text.
                text = transcription["text"]
                print(f"You: {text}")
                # Sends transcribed text to the LLM for processing, this returns a response and any detected actions.
                result = self.llm.process_query(text)
                response_text = result["response"]
                action = result.get("action")

                # If an action is detected and it is a Spotify command, it attempts to execute the command using the SpotifyController.
                # If Spotify is unavailable, it informs the user that Spotify is not configured.
                if action and action["type"] == "spotify" and self.spotify:
                    spotify_result = self._execute_spotify_action(action)
                    if spotify_result.get("success"):
                        response_text = spotify_result.get("message", response_text)
                    else:
                        response_text = spotify_result.get("message", "Sorry, I couldn't execute that Spotify command.")
                elif action and action["type"] == "spotify":
                    response_text = "Spotify is not available. Please check your Spotify configuration."

                # Prints the response from the LLM, saves it as a WAV file, reads it, resamples it if necessary, 
                # and plays it back to the user through the audio output.
                print(f"{self.name}: {response_text}")
                self.tts.synthesize(response_text, self.tts_file)
                tts_audio, tts_sr = sf.read(self.tts_file)
                if tts_sr != self.mic_rate:
                    tts_audio = librosa.resample(tts_audio.astype("float32"), orig_sr=tts_sr, target_sr=self.mic_rate)
                self.audio.play(tts_audio, sample_rate=self.mic_rate)
            # Catches any unexpected errors during the main loop, logs the error
            # and pauses briefly before continuing to listen for the wake word again.
            except Exception as e:
                logger.error(f"Error: {e}", exc_info=True)
                time.sleep(1)

# Runs the SmartAssistant if this script is executed directly. 
# This creates an instance of SmartAssistant and calls its run method to start the main loop.
if __name__ == "__main__":
    SmartAssistant().run()
